[versions]
kotlin = "2.3.21"
ktor = "3.5.0"
coroutines = "1.11.0"
netty = "4.2.10.Final"
hikari = "7.0.2"
argon2 = "2.12"
lettuce = "7.5.0.RELEASE"
minio = "9.0.1"
serialization = "1.11.0"
serialization-plugin = "2.2.21"
snake-yaml = "2.6"
postgresql = "42.7.11"
kotlinx-html = "0.12.0"
kotlinx-css = "2026.5.6"
koin = "4.2.1"
ktorm = "4.2.0"
logback = "1.5.32"
bouncy-castle = "1.84"
agp = "9.0.1"
coreKtx = "1.18.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.13.0"
composeBom = "2026.05.01"

[libraries]
ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktor" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "coroutines" }

serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "serialization" }
serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
serialization-cbor = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-cbor", version.ref = "serialization" }
snake-yaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snake-yaml" }

postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

netty = { module = "io.netty:netty-all", version.ref = "netty" }
netty-epoll = { module = "io.netty:netty-transport-native-epoll", version.ref = "netty" }

hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }

argon2 = { module = "de.mkammerer:argon2-jvm", version.ref = "argon2" }

lettuce = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }

minio = { module = "io.minio:minio", version.ref = "minio" }

ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-websockets = { module = "io.ktor:ktor-server-websockets" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder" }
ktor-server-host-common = { module = "io.ktor:ktor-server-host-common" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-resources = { module = "io.ktor:ktor-server-resources" }
ktor-server-auto-head-response = { module = "io.ktor:ktor-server-auto-head-response" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors" }
ktor-server-caching-headers = { module = "io.ktor:ktor-server-caching-headers" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression" }
ktor-server-compression-zstd = { module = "io.ktor:ktor-server-compression-zstd" }
ktor-server-conditional-headers = { module = "io.ktor:ktor-server-conditional-headers" }
ktor-server-http-redirect = { module = "io.ktor:ktor-server-http-redirect" }
ktor-server-hsts = { module = "io.ktor:ktor-server-hsts" }
ktor-server-forwarded-header = { module = "io.ktor:ktor-server-forwarded-header" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-serialization-kotlinx-cbor = { module = "io.ktor:ktor-serialization-kotlinx-cbor" }

kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinx-html" }
kotlin-css = { module = "org.jetbrains.kotlin-wrappers:kotlin-css-jvm", version.ref = "kotlinx-css" }

koin-ktor = { module = "io.insert-koin:koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j", version.ref = "koin" }

ktorm-core = { module = "org.ktorm:ktorm-core", version.ref = "ktorm" }
ktorm-psql = { module = "org.ktorm:ktorm-support-postgresql", version.ref = "ktorm" }

logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

bouncy-castle = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncy-castle" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization-plugin" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }