package com.github.huymaster.server.api.security

/**
 * A marker interface representing Key Encapsulation Mechanism (KEM) capabilities.
 * Used primarily in Post-Quantum Cryptography (PQC) to securely transfer symmetric keys
 * using asymmetric public key cryptography.
 *
 * @param P for encapsulation, the public key.
 * @param S for decapsulation, the private key.
 * @param O the type of the shared secret key output generated by the mechanism.
 */
interface KeyEncapsulation<in P, in S, out O> : Security {
    /**
     * Represents the sender's role in a KEM exchange.
     * Generates a random shared secret and encrypts (encapsulates) it into a ciphertext.
     */
    interface KeyEncapsulator<in P, out O> {
        /**
         * Encapsulates a randomly generated shared secret using the receiver's public key [P].
         *
         * @param publicKey The recipient's public key used to encrypt the shared secret.
         * @return A [Pair] containing:
         * - The ciphertext [ByteArray] to be transmitted over the insecure channel.
         * - The established shared secret key of type [O].
         */
        fun encapsulate(publicKey: P): Pair<ByteArray, O>
    }

    /**
     * Represents the receiver's role in a KEM exchange.
     * Recovers the shared secret from the received ciphertext using a private key.
     */
    interface KeyDecapsulator<in S, out O> {
        /**
         * Decapsulates the ciphertext using the private key [S] to recover the shared secret.
         *
         * @param ciphertext The encrypted key capsule received from the encapsulator.
         * @param privateKey The recipient's private key used to decrypt the ciphertext.
         * @return The recovered shared secret key of type [O].
         */
        fun decapsulate(ciphertext: ByteArray, privateKey: S): O
    }

    /**
     * The encapsulator instance responsible for generating shared secrets and ciphertexts.
     */
    val encapsulator: KeyEncapsulator<P, O>

    /**
     * The decapsulator instance responsible for recovering shared secrets from ciphertexts.
     */
    val decapsulator: KeyDecapsulator<S, O>

    /**
     * Encapsulates a randomly generated shared secret using the receiver's public key [P].
     *
     * @param publicKey The recipient's public key used to encrypt the shared secret.
     * @return A [Pair] containing:
     * - The ciphertext [ByteArray] to be transmitted over the insecure channel.
     * - The established shared secret key of type [O].
     */
    fun encapsulate(publicKey: P): Pair<ByteArray, O> = encapsulator.encapsulate(publicKey)

    /**
     * Decapsulates the ciphertext using the private key [S] to recover the shared secret.
     *
     * @param ciphertext The encrypted key capsule received from the encapsulator.
     * @param privateKey The recipient's private key used to decrypt the ciphertext.
     * @return The recovered shared secret key of type [O].
     */
    fun decapsulate(ciphertext: ByteArray, privateKey: S): O = decapsulator.decapsulate(ciphertext, privateKey)
}